### ISSUE TITLE
Suporte e-sedex pela gem "correios-frete"

### ISSUE THREAD

**Issue by leosmeira** [thitemple/spree-correios-shipping#1]
Bom dia,

A gem "correios-frete"  está com suporte a E-SEDEX.

Você poderia colocar este suporte na sua GEM ?

Desde já agradeço.

Att

**Comment by thitemple** [comment]
Posso sim, farei isso assim que possível

**Comment by leosmeira** [comment]
OK,
Muito Obrigado!

**Comment by thitemple** [comment]
Opa, desculpa no responder, foi meio corrido hj.
Ento, eu fao rails h quase 1 ano e meio.
Esse  o 1o projeto de ecommerce que eu fao e resolvi usar o spree, at
agora ele me atendeu e parece que o pessoal que cuida dele  bem ativo. Essa
foi a principal razo que eu usei pra escolhe-lo.
Ele  bem simples e acho que em algumas coisas ainda pode melhorar, mas
tambm  fcil de aprender e customizar.
Quais outros vc j usou?
.
Thiago Temple
http://vintem.com.br
http://longedecasa.vintem.com.br

2011/7/19 leosmeira <
reply@reply.github.com>

**Comment by thitemple** [comment]
Implementado

**Comment by leosmeira** [comment]
Em Rails, eu tambm acho que  o melhor, mais completo e mais ativo.

Mas vendo outras opes como MAGENTO(php), d pra notar que o SPREE precisa
de uma comunidade maior de desenvolvedores.

2011/7/20 vintem <
reply@reply.github.com>
